local colors = {
    black = "#06080A",
    bg0 = "#1A1B26",
    bg1 = "#1A1B2A",
    bg2 = "#B44B69",
    bg3 = "#353945",
    bg4 = "#4A5057",
    bg5 = "#282C34",
    highlight = "#1F202E",
    visual = "#42424D",
    bg_red = "#FE6D85",
    bg_green = "#98C379",
    bg_blue = "#9FBBF3",
    diff_red = "#773440",
    diff_green = "#587738",
    diff_blue = "#2A3A5A",
    diff_add = "#1E2326",
    diff_change = "#262B3D",
    diff_delete = "#281B27",
    diff_text = "#1C4474",
    fg = "#A0A8CD",
    red = "#EE6D85",
    orange = "#B77A57",
    yellow = "#D7A65F",
    green = "#96B582",
    blue = "#7199EE",
    cyan = "#07C2C5",
    purple = "#9962A7",
    purple2 = "#B893C2",
    grey = "#4A5057",
    pink = "#DD225A",
    none = "NONE",
}

return {
    normal = {
        a = { bg = colors.blue, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    insert = {
        a = { bg = colors.red, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    visual = {
        a = { bg = colors.green, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    replace = {
        a = { bg = colors.pink, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    command = {
        a = { bg = colors.cyan, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    terminal = {
        a = { bg = colors.purple, fg = colors.bg0, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
    inactive = {
        a = { bg = colors.bg1, fg = colors.grey1, gui = "bold" },
        b = { bg = colors.purple, fg = colors.bg0 },
        c = { bg = colors.bg0, fg = colors.purple },
    },
}
